### ISSUE TITLE
The page is frizen in hammerhead-playground

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#1205]
Converted from [the question](https://testcafe-discuss.devexpress.com/t/content-of-the-iframe-in-which-the-test-is-currently-operating-did-not-load/258/5)
https://bex-demo.finartz.com/checkout
This is caused by `bex-expess.js` recource loading

**Comment by LavrovArtem** [comment]
fixed by https://github.com/DevExpress/testcafe-hammerhead/pull/1206

**Comment by utkusonmez** [comment]
Thanks for fix, when will it be released?

**Comment by miherlosev** [comment]
Today or tomorrow we'll release a new version of TestCafe.

**Comment by AlexanderMoskovkin** [comment]
@utkusonmez We've published the fix in the latest `alpha` version.
`npm install -g testcafe@alpha` or `npm install -g testcafe@0.17.0-alpha2`

**Comment by ismailgmutlu** [comment]
Our test is still not working properly. switchtoIframe function seems to be the problem. Because if we remove it from the test it passes. It throws 

"The specified selector does not match any element in the DOM tree."

error right now. In addition after clicking the button, it does not load the iframe, if we add more steps to the test.

**Comment by LavrovArtem** [comment]
Hi @ismailgmutlu,
Could you please provide URL to your page, if it possible?

**Comment by ismailgmutlu** [comment]
I am running the same [test](https://testcafe-discuss.devexpress.com/t/content-of-the-iframe-in-which-the-test-is-currently-operating-did-not-load/258/5) with the same URL and uploaded my version to 0.17.0-alpha2.

**Comment by LavrovArtem** [comment]
Hi @ismailgmutlu,
I have investigated your test and it is incorrect. I made some remarks in it, see below:

```javascript
import { Selector } from 'testcafe';

fixture `databasetesting`
    .page `http://bex-demo.finartz.com/checkout`;

const loginButton = Selector('#test');

test(`Test Speed`, async t => {
    await t
        .maximizeWindow()
        .hover(loginButton)
        .expect(loginButton.visible).ok()
        .switchToIframe(loginButton)
        // remarks
        .click('#loginButton')
        .typeText('#username', 'admin')
        .typeText('#password', 'admin')
        .click('#login');
});
```

**Comment by ismailgmutlu** [comment]
You are right, it is working now. Thanks for help.
