### ISSUE TITLE
Page doesn't load in hammerhead-playground

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#1389]
Based on [question ](https://testcafe-discuss.devexpress.com/t/browser-hangs-when-running-testcafe-locally/623)
url is private 
It happens due to error in `generateCallExpression` method: 
`(node:2717) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: First argument must be a string or Buffer`

**Comment by neilmatillano** [comment]
Do you have any timeline or date for this issue to be resolved or new version with this fix to be available?

**Comment by miherlosev** [comment]
Hi @neilmatillano 
We plan to fix this issue during [Sprint 10](https://github.com/DevExpress/testcafe-hammerhead/milestone/16). I cannot provide you with a strong timeline, but usually it takes about 2-3 weeks.
Also, when the issue will be fixed, we will publish a new testcafe version at once.

**Comment by LavrovArtem** [comment]
The fix is published in `testcafe@0.18.6-dev20171207`

**Comment by neilmatillano** [comment]
Great! Can you give me the link where I can get the latest version with the fix?
Thanks!

**Comment by neilmatillano** [comment]
I tried and I get this new error ( different from previous one I got), but now it automatically closes the browser:

✖ InitialTest

   1) Error on page "https://...":

      Uncaught SyntaxError: 'super' keyword unexpected here

      Browser: Chrome 62.0.3202 / Mac OS X 10.13.1



 1/1 failed (5s)

**Comment by LavrovArtem** [comment]
Please try to run TestCafe with --skip-js-errors. ([more information](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors)):

**Comment by LavrovArtem** [comment]
I've investigated the error and found another our problem. 
We will let you know when we release a version with the fix.

**Comment by neilmatillano** [comment]
Thank you @LavrovArtem , yes i added the --skip-js-errors, no crash but the page is still not loading properly.

**Comment by neilmatillano** [comment]
Do you have an estimate for the release with the fix for this new issue? @LavrovArtem 
Thanks!

**Comment by miherlosev** [comment]
We will publish the release with a fix next week.

**Comment by LavrovArtem** [comment]
@neilmatillano The fix is published in `testcafe@0.18.6-dev20171211`

**Comment by neilmatillano** [comment]
@LavrovArtem , page seems to finally get loaded now. I will check further by adding more tests. Thank you all for the reactivity!

**Comment by LavrovArtem** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/1410

**Comment by EItanya** [comment]
I just downloaded version `testcafe@0.18.6-dev20171211` and I am still seeing the original error that was posted in the original thread. I am running the same environment as well.

**Comment by miherlosev** [comment]
Hi @EItanya.
Try to use the latest version - `testcafe@0.18.7-dev20180206` and tell us about results..

**Comment by EItanya** [comment]
Hi, @miherlosev, Thanks so much for the rapid response. I downloaded the newest version and the tests now start up without the error, but nothing displays so the test ends up failing. I navigate to the URL normally and the website shows up, but when I input the same URL into the test it loads, but nothing renders.

**Comment by miherlosev** [comment]
>  I navigate to the URL normally

Is your site public? Could you, please, provide an url?

**Comment by EItanya** [comment]
No it is not, sorry

**Comment by miherlosev** [comment]
In this case, we need an example to reproduce. By the description you provided, it is a difficult to determinate the reason of the problem. Or we can try to organize an remote session using Skype.

**Comment by EItanya** [comment]
I talked it over with my team and that would be great. How would you like to go about scheduling that?

**Comment by miherlosev** [comment]
Write me on mikhail.losev@devexpress.com.
I will send you an invitation to the TestCafe's Slack channel.
