### ISSUE TITLE
Hammerhead doesn't inject scripts into an iframe on iOS 9.3

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#672]
I have a simple page that contains a same-domain iframe:
```html
<body>
<iframe id="iframe" src="iframe.html"></iframe>
</body>
```

As a result this iframe has the following markup in Safari on iOS 9.3 with hammerhead playground:
```html
<iframe id="iframe" src="http://172.22.2.200:1401/H1d_dk-w!i/http://172.22.2.200/iframe.html" src-hammerhead-stored-value="iframe.html">
  <html>
    <head>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta charset="utf-8">
      <title>iframe</title>
      <!-- 
      Here should be hammerhead scripts but there are no
      -->
    </head>
    <body>
    </body>
  </html>
</iframe>
```

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Problem occurs because you check the scenario in simulator.
It is characteristic of the playground.
Hammerhead scripts are resolved with `localhost` hostname and don't loaded (see errors in Network tab).
Change `localhost` to your IP ([one](https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/playground/server.js#L40), [two](https://github.com/DevExpress/testcafe-hammerhead))/blob/master/test/playground/server.js#L73)) and all should works right.

**Comment by AlexanderMoskovkin** [comment]
> Change localhost to your IP (one, two) and all should works right.

The issue is still reproduced with this changes. 
But I've investigated the issue and found out that it happens because of the [bug in iOS 9.3](https://bugs.webkit.org/show_bug.cgi?id=155754). Browser sends a request for an iframe page with `header['accept']= '*/*'` instead of `text/html`. As a result we set the `isPage` flag to `false`[here](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/context.js#L60) and don't process this as a page (don't place scripts in the header).
The bug is fixed in iOS 9.3.2. So we can keep this issue closed
